//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2027.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2027.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic effects (DX10).
        /// </summary>
        public static string Effects_D3D10 {
            get {
                return ResourceManager.GetString("Effects_D3D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic effects (DX9).
        /// </summary>
        public static string Effects_D3D9 {
            get {
                return ResourceManager.GetString("Effects_D3D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced effects.
        /// </summary>
        public static string Effects_D3D9_ENB {
            get {
                return ResourceManager.GetString("Effects_D3D9_ENB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic effects (OpenGL).
        /// </summary>
        public static string Effects_OpenGL {
            get {
                return ResourceManager.GetString("Effects_OpenGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use advanced effects.
        /// </summary>
        public static string EnbLabel {
            get {
                return ResourceManager.GetString("EnbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid install path. Please reinstall 2027..
        /// </summary>
        public static string ErrorInvalidDir {
            get {
                return ResourceManager.GetString("ErrorInvalidDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version of Deus Ex. Please install the 1.112fm patch..
        /// </summary>
        public static string ErrorInvalidVersion {
            get {
                return ResourceManager.GetString("ErrorInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string ForumLabel {
            get {
                return ResourceManager.GetString("ForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ResolutionCustomLabel {
            get {
                return ResourceManager.GetString("ResolutionCustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen resolution.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in windowed mode.
        /// </summary>
        public static string RunInWindow {
            get {
                return ResourceManager.GetString("RunInWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch game.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
    }
}
